version: 'v2.28.1'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017

  server:
    build: .
    image: aidenjaney/passwordmanager_backend
    ports:
      - 8080
    links:
      - mongo-db
  
  client:
    build: client
    image: aidenjaney/passwordmanager_frontend
    ports:
      - 4200